"""initial migration

Revision ID: b741ba908f79
Revises: 
Create Date: 2020-06-12 01:32:40.828206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b741ba908f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GPB', 'RUB', 'BTC', name='currenciesenum'), nullable=False),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('currency')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('_balance', sa.Float(precision=28), nullable=True),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GPB', 'RUB', 'BTC', name='currenciesenum'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'currency'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_new_balance', sa.Float(precision=28), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_new_balance', sa.Float(precision=28), nullable=False),
    sa.Column('currency', sa.Enum('EUR', 'USD', 'GPB', 'RUB', 'BTC', name='currenciesenum'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'currency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('currency')
    # ### end Alembic commands ###
